### ISSUE TITLE
Capture File Fill Diabetes and Maternity Values error

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#266] opened 2015-10-09 13:46 UTC
A Benefit Expert has reported a calculator error that does not allow her to generate a document thereby preventing her from completing her job. 

![image](https://cloud.githubusercontent.com/assets/10272072/10395284/1134528a-6e6a-11e5-9ca1-4f46eed174c9.png)

On further analysis, it seems it's the diagnostic cost share that is tripping the Type II diabetes calculator - 
![image](https://cloud.githubusercontent.com/assets/10272072/10395287/1e87f900-6e6a-11e5-9039-1714ed614fc0.png)

Please fix this issue so that, just like with other calculator related services only the first cost share of the service is taken into consideration for the calculator input and that adding such cost share does not prevent user from generating the document.

**Comment by michparrish** [comment] 2015-10-09 19:22
Hi Gaurang,
We've updated the calculator to recognize only the first cost share. I tested and did not receive the error message. Please test in pclient5 and let me know if it's successful and we can move to Prod.
Thank you.

**Comment by g4gaurang** [comment] 2015-10-13 14:31
Not Fixed.

![image](https://cloud.githubusercontent.com/assets/10272072/10457749/85a967da-7195-11e5-938f-60dc98f33232.png)

![image](https://cloud.githubusercontent.com/assets/10272072/10457693/60e95dec-7195-11e5-9dad-1fa3dfa1c91d.png)

**Comment by michparrish** [comment] 2015-10-13 14:36
please try removing the space between the semi-colon and end of the first statement

**Comment by g4gaurang** [comment] 2015-10-13 14:40
It did not make any difference. I still get the same error. Also, please code to discount the extra spaces if there are any. A user could easily add in extra spaces without realizing.

**Comment by g4gaurang** [comment] 2015-10-13 14:42
> michparrish closed this 7 minutes ago

Why did you close it ? @michparrish

**Comment by michparrish** [comment] 2015-10-13 14:44
that's bizarre - I didn't close it. Unless I clicked the 'close and comment' button instead of just 'comment'. My apologies.

**Comment by TimHeasley** [comment] 2015-10-13 17:31
Gaurang,
The calculator has been updated in Production and is ready for retest. 
Prior to moving the calculator, I tested the new calculator in PClient5 and it worked correctly.

The issue seemed to be caused by there being more text after “% coinsurance”. So the formula recognized it as being Coinsurance and only trimmed the “% coinsurance” part.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-10-14 13:49
Still not fixed. 

![image](https://cloud.githubusercontent.com/assets/10272072/10485492/7de3510a-7258-11e5-92ce-01488ad936dc.png)

![image](https://cloud.githubusercontent.com/assets/10272072/10485523/ad47ff04-7258-11e5-9262-e51e636c1954.png)

**Comment by TimHeasley** [comment] 2015-10-15 14:48
Gaurang,
The calculator file has been updated to work for both coinsurance and copays now. 
Ready for retesting.
Thank you,
Tim

**Comment by g4gaurang** [comment] 2015-10-19 13:26
Not Fixed. The calculations do not match now. See attached screenshots and PDF.

![image](https://cloud.githubusercontent.com/assets/10272072/10578901/1b15c2c6-7643-11e5-9f63-fa0f80ac7d1b.png)

[MasterMedicalTest.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/16010/MasterMedicalTest.pdf)

![image](https://cloud.githubusercontent.com/assets/10272072/10578943/4cd0c50e-7643-11e5-8691-c15e47dbd78a.png)

**Comment by TimHeasley** [comment] 2015-10-19 13:58
Guarang,
Thank you for testing, we will update and let you know when it is ready for retest
Tim

**Comment by TimHeasley** [comment] 2015-10-19 19:46
Gaurang,
 The calculator file has been updated in PClient5 and is ready for retest.
 Thanks,
 Tim

**Comment by g4gaurang** [comment] 2015-10-22 18:28
Changes look good. Please move to production.

**Comment by willdwyer** [comment] 2015-11-02 17:07
Hi Tim,

Was this moved to production?  Just want to confirm before proceeding to re-test.

**Comment by TimHeasley** [comment] 2015-11-02 17:36
Hi Will,
We are working on fixing Issue #277 and hope to have it ready for you to retest in PClient5 today.  We can then move the calculator to Production that fixes both items.
Thanks,
Tim

**Comment by michparrish** [comment] 2015-11-04 19:52
calculator has been loaded to Prod. Please test and close item as you see fit.

**Comment by willdwyer** [comment] 2015-11-04 21:21
Looks fixed.  This defect is being closed.

**Closed as completed by willdwyer** 2015-11-04 21:21 UTC
Labels: Type-Defect, Priority-ShowStopper, Build-P19.5.11.16, Environment-Production, Status- BCBSMA Retest
