### ISSUE TITLE
Job number not incrementing in ascending order in Production

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#216] opened 2015-07-17 22:17 UTC
```
What steps will reproduce the problem?
1.Login to production as administrator and navigate to content library
2. Navigate to BCBSMA/Plan/Drafts/Custom folder to view custom HR plan designs
3. See attached screenshot.

Actual Result:
The job number is not incrementing in ascending order,the number sequence seems 
to be going back and forth. 



Expected Result:
It is important for the job number sequence to increment in ascending order 
because this is how the benefit Experts will identify the order of jobs coming 
in over a period of time.


Test Case # Lisa reported this issue in production



```

Original issue reported on code.google.com by `BCBSMAMa...@gmail.com` on 30 Jun 2015 at 3:35

Attachments:
- [JobNumberSequenceProduction.JPG](https://storage.googleapis.com/google-code-attachments/bcbsmaissuestracker/issue-216/comment-0/JobNumberSequenceProduction.JPG)

**Comment by markderg** [comment] 2015-08-21 02:36
Closing issue due to FM Pro issue being assessed/implemented at this time.  No action needs to be taken.  Issue will be reopened pending outcome of FM Pro enhancement.  Thx, Mark

**Closed as completed by markderg** 2015-08-21 02:36 UTC
Labels: Priority-High, Type-Defect, auto-migrated, Build-P19.5.11.16, Milestone-Post_1.1, Environment-Production, HR_FixType-HR_Product

**Comment by g4gaurang** [comment] 2015-08-28 16:15
This is a production bug which HR is unable to fix. The FMPro# enhancement in the system, once functioning correctly, will mitigate the level of risk caused by this issue and relegates the importance of the HR job number to an extent.
