### ISSUE TITLE
Benefit cost share changed to junk value

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#181] opened 2015-07-17 22:14 UTC
```
What steps will reproduce the problem?
1. Log on to PClient5 as a BCBSMA Administrator
2. Click on Manage Plan
 Enter search criteria:
 Effective Date - 2015
 Financial Arrangement - Insured
 Market Segment - Large Group 100+
 Product Type - PPO
 Plan Type - Custom
 Click - Show Me Plans"

3. Select 
3418172 Network Blue New England Options Deductible v.4 Gold Medal Bakery and 
click plan document options and 
4.Generate Final PDF with disclosures through plan options. 
5. preview page 2


Actual Result:
The Enhanced benefit tier value for other practitioner office visit is changed 
to #N/A even where no such change was made. This cost share was not even 
modified during customization and it should been the default value from 
standard base plan


Expected Result:
System should not junk benefit cost share in this manner.

Test Case #
E2E_14
```

Original issue reported on code.google.com by `g4gaur...@gmail.com` on 11 Jun 2015 at 3:01

Attachments:
- [3418172 Network Blue New England Options Deductible v.4 Gold Medal Bakery.JPG](https://storage.googleapis.com/google-code-attachments/bcbsmaissuestracker/issue-181/comment-0/3418172 Network Blue New England Options Deductible v.4 Gold Medal Bakery.JPG)

**Comment by g4gaurang** [comment] 2015-10-27 15:44
A BE user experienced a situation where when she entered text appending an existing L&E value/text for Imaging on the interface and save it, it turned into a junk value (#value!) 

Plan design is 3459290_Stratus Technologies_Network_Blue_NE_Ded_154799BS    

This may or may not be reproducible immediately when you try to replicate it on Pclient5/Prod. but we would like you to review and fix the capture file formula for invalid references and ensure this does not happen again.

![image](https://cloud.githubusercontent.com/assets/10272072/10763193/5c037eba-7c9f-11e5-9e82-70d0a7527a80.png)

![image](https://cloud.githubusercontent.com/assets/10272072/10763201/65ae043a-7c9f-11e5-8090-602dc09fdd93.png)

![image](https://cloud.githubusercontent.com/assets/10272072/10763218/78738cc0-7c9f-11e5-9b54-1a8a48a72d75.png)

**Comment by TimHeasley** [comment] 2015-10-27 16:45
Gaurang,
Can you offer more detail as to what the text was that the BE entered?  
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-10-27 17:35
Here it is
Deductible applies first; copayment applies per category of test / day; copayment limited to $375 per member per calendar year; pre-authorization required for certain services

**Comment by TimHeasley** [comment] 2015-10-27 20:35
Guarang, 
We have tested out the values in multiple workbooks with the Limitations string you sent and we are not seeing any errors in PClient5.   Please retest at your convenience.
Thank you,
Tim

**Comment by g4gaurang** [comment] 2015-10-27 20:48
Tim, as I indicated above, you may or may not be able to reproduce the defect immediately but the fact is it has occurred on the said plan in production. The question is can you investigate and/or tweak your cell reference formula for that field appropriately so that the #value! does not show up again unexpectedly or do you do nothing and just wait for another recurrence of a similar issue in the future ?

**Comment by sayotte7701** [comment] 2015-10-27 21:17
Hi Guarang.   I don't think our intention is to do nothing on this.   What would really help us is to have the text string which caused the issue.  Having that data would allow us to reproduce the issue and then take decisive action on tweaking the formula.  What I'll do is carve out some time tomorrow to see if I can reproduce the issue.   If I cannot, we can close this issue for now as not reproducible.   If it does happen again, lets try and get the exact text string.

**Comment by g4gaurang** [comment] 2015-10-27 21:49
> Here it is
> Deductible applies first; copayment applies per category of test / day; copayment limited to $375 per member per calendar year; pre-authorization required for certain services

This is the exact string that the BE provided.

**Comment by g4gaurang** [comment] 2015-10-28 15:17
Can you put in a IFERROR(value, value_if_error) error handling mechanism for this service to ensure such error messages do not leak out to the UI/document ?

**Comment by g4gaurang** [comment] 2015-10-29 14:40
The BE users are running into this same issue on the same plan again as they finalize the plan to send to the account.  I am attaching the draft SBC here. copy the Imaging L&E from the SBC document as is and paste it in the  Imaging L&E field on the UI and click save. Notice the #value! tag re-appear.

Plan design is 3459290_Stratus Technologies_Network_Blue_NE_Ded_154799BS

the BE user recreated this issue a few times.

![image](https://cloud.githubusercontent.com/assets/10272072/10821485/0ea2d14e-7e29-11e5-8295-0b92cce881bc.png)

![image](https://cloud.githubusercontent.com/assets/10272072/10821493/1da049d8-7e29-11e5-8b4f-7a54885fbe7b.png)

[154799BS_Stratus Technologies_NBNE_CLIENT_10-29-15.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/23414/154799BS_Stratus.Technologies_NBNE_CLIENT_10-29-15.pdf)

**Comment by michparrish** [comment] 2015-10-29 15:01
Thanks, Gaurang - this seems to happen after 2 or more saves, but not one. We're investigating the issue.

**Comment by TimHeasley** [comment] 2015-10-29 19:17
Guarang,
We have updated the logic if an error (junk value) is encountered, the original text in the field will remain.  It has been tested in PClient5 and confirmed working.
Please retest at your convenience.
Thank you,
Tim

**Comment by g4gaurang** [comment] 2015-10-29 20:39
Tim, can you tell us what you changed in the logic ?

**Comment by TimHeasley** [comment] 2015-10-29 20:51
Guarang,
The original Imaging Limitations logic is still in place and will work as intended. If, for some reason, it errors out on the back end, whatever the user has entered will be kept and will appear correctly. Same thing if the user selects “No cascade” for Imaging Cascade. It allows the user to enter whatever string into limitations they want without the preset logic interfering, as was the intention with it.

Essentially, in addition to fixing what was causing the error in the first place, there’s an overarching IFERROR() around it that will keep whatever the user entered if the Imaging formula errors out.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-10-30 13:51
Changes look good on Pclient5. Please move to production.

**Comment by TimHeasley** [comment] 2015-10-30 13:55
Guarang,
Thank you for testing. We will move to Production and let you know when it is ready for retest.
Tim

**Comment by TimHeasley** [comment] 2015-10-30 18:18
Guarang,
The changes have been moved to Production and are ready for retest.
After approval/confirmation please close the issue.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-11-04 18:16
Looks good in production.

**Closed as completed by g4gaurang** 2015-11-04 18:16 UTC
Labels: Type-Defect, auto-migrated, Milestone-Release1.1, Priority-ShowStopper, Build-P19.5.11.16, Environment-Pclient5, Environment-Production, Status- BCBSMA Retest
