### ISSUE TITLE
Plan configurator error 

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#325] opened 2015-12-17 16:19 UTC
BE went to make edits to a job that came back from the client. When he goes in to make them, he get a configurator error and system won’t load the plan design.
Please fix ASAP.

![screen shot 2015-12-17 at 9 02 59 am](https://cloud.githubusercontent.com/assets/10272072/11874866/baab7408-a4af-11e5-9fea-e3d66a21f608.png)
![screen shot 2015-12-17 at 9 04 31 am](https://cloud.githubusercontent.com/assets/10272072/11874867/bac36c70-a4af-11e5-898c-68276ad894b3.png)

**Comment by TimHeasley** [comment] 2015-12-17 17:32
Guarang,
We are testing to determine the root cause. We will let you know what we find.
Thank you,
Tim

**Comment by TimHeasley** [comment] 2015-12-17 19:37
Guarang,
We are having the QA support team review this plan, we were able to recreate the issue, but not able to identify the cause of the issue.  
As a temporary workaround, you are currently able to create another custom plan from this “bad” plan as an option.  We have tested this process and it does work, with a new job number assigned. 
We will let you know on the QA team's findings as soon as we hear them.
Thanks,
Tim

**Comment by TimHeasley** [comment] 2015-12-21 21:55
Guarang,
The support team has found the following  - "It seems to be that particular plan has the issue. That plan id seems to be corrupted on the system.  The workaround is to recreate a custom plan from original standard plan. Or from this plan create another custom plan then edit it in Plan Configurator.”
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-12-22 19:41
> Guarang,
> The support team has found the following - "It seems to be that particular plan has the issue. That plan id seems to be corrupted on the system

Tim, Can you explain what the technical definition of "corrupted" is in this context ? and how it got corrupted within the system ?

**Comment by willdwyer** [comment] 2016-01-05 15:33
Hi Tim,

I have been out of the office for the past 2 weeks and am seeing this now.  Has any light been shed on this?  I also looked at issue #327 and noticed the suggested workaround was to create a custom plan from 800195 and have that replace the standard.  That workaround would not work as users must allocate customs from the standard design of 800195.

Also, if a user is able to create a custom from this standard plan (800195), make no edits and then generate and save as a new plan, why wouldn't we able to fix this corrupt system ID?

**Comment by michparrish** [comment] 2016-01-05 16:13
Will,
I just tested something else in our shadow environment and it worked. If you make a copy of this plan, check the Keep History and Keep Attributes boxes, you will have a new exact copy of the plan that works with the configurator. The old, corrupted plan can be deleted and the  new one would be renamed with the correct FMPro code (the new copy is automatically renamed with the ellipsis at the end, so you have to use the Rename tool as well). The issue is with the current revision of the custom plan so we'd want to remove that one from the system and from use.
I can take care of this for you but Sean Harvey is currently locked in the plan. If you can have him Revert the plan, I can make the copy/bring over all version history and attributes and rename it for you.

**Comment by willdwyer** [comment] 2016-01-05 20:14
Hi Michelle,

I just did some testing in the shadow environment...

Here is the issue... I am unable to replicate that exact Edit Plan Configuration defect, even after creating a custom plan from that standard plan 800195, and going to edit that custom plan created.  I also followed the steps of making a copy of standard plan 800195, with Keep History and Keep Attributes boxes checked, and then attempting to edit that plan.  I did not encounter an issue.  This doesn't appear to be a constant-occurring defect.

Please move this code to production, and make the copies of these plans, and we will test in the production environment.

Thanks,

**Comment by michparrish** [comment] 2016-01-05 20:20
Thank you for testing Will - we were able to recreate so I'm not sure how you weren't!
Just a note - there is no code to be moved. It's really just creating new plans copies from the ones that are there and deleting the old. I will make a copy of 3481383 for now. We are contemplating another process for the source corrupt file 800195. Similar to a copy but we need to do testing on it first before presenting the idea to you.

**Comment by willdwyer** [comment] 2016-01-05 20:30
OK, thanks Michelle.

As long as users don't encounter this issue in the future when creating customs out of plan 800195, or customs that originated from that standard, then it works for me.

We will leave this open until the issue regarding corrupt file 800195 is resolved.

**Comment by michparrish** [comment] 2016-01-05 20:32
No problem, the new 3481383 has been created and the old one deleted. 

for our analysis on the other one, I'd assume you'd like to keep the history of 800195?

**Comment by willdwyer** [comment] 2016-01-05 21:01
Yes, please.

**Comment by michparrish** [comment] 2016-01-05 21:02
ok, thank you.
btw - I learned of a way where your team can see back more than 3 historic versions. I'll post the instructions into that specific GH item.

**Comment by willdwyer** [comment] 2016-01-14 20:05
Hi Michelle,

Just want to confirm that this is all set?  That the corrupt system code for 800195 has been fixed, and we can close this item?

I just retested/regenerated from standard plan 800195, and seemed to be OK on our end.

**Comment by michparrish** [comment] 2016-01-14 20:48
Hi Will,
If you're no longer experiencing issues with this plan, we can close it. To be safe, we were going to generate a new copy of that Standard plan but it looks like things are working fine so we don't need to go to that extent. We ran the same tests as you and received the same results.
please feel free to close this item if you see fit. Thanks!

**Comment by willdwyer** [comment] 2016-01-15 15:51
This issue, as well as issue #327 are being closed.

**Closed as completed by willdwyer** 2016-01-15 15:51 UTC
Labels: Type-Defect, Priority-ShowStopper, Build-P19.5.11.16, Environment-Production, Status- BCBSMA Retest, To_Be_Addressed_In_V1
