### ISSUE TITLE
Error Re-generating Standard 2015 SBCs through HR system

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#249] opened 2015-08-24 14:16 UTC
We are unable to re-generate any Standard 2015 SBCs out of the HR system both on Pclient5 and Production. This is the error message we get – 
Can you look into this ? This will be showstopper should a BE decide to update a 2015 Standard SBC plan design and re-generate through the system.

![image](https://cloud.githubusercontent.com/assets/10272072/9442263/012dc4e2-4a49-11e5-9cfa-f2def2eb54c5.png)

![image](https://cloud.githubusercontent.com/assets/10272072/9442267/0796d4c2-4a49-11e5-8383-2fa7938d7314.png)

**Comment by markderg** [comment] 2015-08-24 17:11
Gaurang:  Since we updated only 2016 plans with the government mandated changes (item 231); 2015 plans are not in sync and need to be updated to prevent this error.  We need approval from BCBSMA to make changes to the 2015 plans.  Please let us know...Thx, Mark

**Comment by g4gaurang** [comment] 2015-08-24 17:48
@markderg Are you suggesting you will need to add the new First Page disclaimer Website field also on 2015 plan designs so that both the 2015 and 2016 plan designs are in sync.That way any calculator data/ field extraction logic is uniform across plan designs and does not result into errors ?

Can HR do an impact assessment on their end to confirm that making such a change will not cause any unintended changes to 2015 SBC generation or system as a whole ? We would also like a high level system test plan. 

cc @jddecoste

**Comment by markderg** [comment] 2015-08-24 18:42
As part of 8/24 checkpoint with Abbie and Jenn D. - Confirmed - Generating standard plans out of HR for 2015 due to errors.  HR will asses approach for updating plans, testing approach, and timeline.  Will follow up with BCBSMA.

**Comment by michparrish** [comment] 2015-08-24 19:12
HR proposal:
Update all 2015 plan designs with new First Page Disclaimer Website field so the structure of the plan design coincides with the structure of the 2016 plans and all mappings/calculator configuration/template configuration.
Since the new URL is not needed for 2015 plan designs, we can copy and paste the value from the Website field into this field so the correct value is populated when the document is generated.
The standard plans are not edited using the Configurator, so no workbooks require changes. Templates and calculator have already been updated and tested for the 2016 plans to success. This is simply Check Out plan > Edit > add new field in same location before 'Website' field, copy value from Website field into new field > Save > Close.
This is in the same manner we did this a couple of weeks ago for the 2016 plans, without the additional configuration we've already completed. We will QA by running Plan Output reports to ensure that the field is not missing from any plans, as well as the value.
LOE will be approximately 3 days, end to end.

What we need from BCBS:
Timeframe on when would be best to enter these changes - as they are made in Prod. We will do this during off hours.
Any users currently locked in 2015 Standard plans to Revert/Check In those plans so we do not have to skip any.

Thank you

**Comment by g4gaurang** [comment] 2015-08-26 14:11
Benefit Experts feel  that while this is certainly a showstopper for 2015 SBCs, we are at a stage where we do not expect further changes to 2015 SBCs. In that context we have decided not to make this change (addition of new plan design field to 2015 Plan designs)  because it will not be worth the risk and health check efforts relative to the benefit. This is not to say with certainty that there will not be edits to 2015 standard Plans - in the event there is, it will have to be handled manually outside of the system. BCBSMA does not generate custom 2015 SBCs through the system (this will obviously change for 2016) 

But we want to make sure this is not going to be the case for next year. More specifically, given all the government changes to the 2017 SBC template, a bunch of  HR plan design fields may be added and removed. HR will need to ensure that, at that point, the system will be able to generate BOTH 2016 and 2017 SBCs. If this means re-architecting the calculator extraction criteria to make it field based as opposed to (cell) position based then HR should be prepared to do so. In short, whatever changes necessary for BCBSMA to be able to generate both 2016 and 2017 SBCs. @markderg, HR will need to ensure this will not be a problem going forward.

@jddecoste

**Comment by michparrish** [comment] 2015-08-26 14:47
We will most definitely assess the best way to handle the upcoming changes for 2017. Depending on when we migrate to P2A, we will ensure there is no disruption between the years' plan designs, editing process and SBC generation process.

are we ok to close this item?

**Closed as completed** 2015-08-26 14:59 UTC
Labels: Type-Defect, Priority-ShowStopper, Build-P19.5.11.16, Environment-Pclient5, Environment-Production, P2Advance
