### ISSUE TITLE
Error uploading documents in Content Library - AB-164

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#254] opened 2015-09-03 20:47 UTC
We encountered the following issue this afternoon when uploading custom SBCs in Content Library using Internet Explorer. (Happens with other browsers too)

We tried to upload a word and PDF SBC to the TJX custom folder (See screenshot below)

![image](https://cloud.githubusercontent.com/assets/10272072/9670470/c06b6b84-525a-11e5-837c-ddf6c2aae00a.png)

And we received the following error on the upload screen 
![image](https://cloud.githubusercontent.com/assets/10272072/9670372/2e2a1072-525a-11e5-8aac-be5ad745f814.png)

And then this error when we click submit on the Create New document window/screen

![image](https://cloud.githubusercontent.com/assets/10272072/9670581/2d11017c-525b-11e5-8cc9-dffd9bc4b39d.png)

This functionality worked fine yesterday and even this morning. Please investigate cause and fix. 

CC @jddecoste

**Comment by g4gaurang** [comment] 2015-09-04 15:12
We are having trouble uploading files for 135935BS_Radius Financial_PB$2000. It appears to be the same problem as yesterday. Attached are screen shots. 

![image](https://cloud.githubusercontent.com/assets/10272072/9687123/a335fe76-52f5-11e5-89d5-45c4d0f6432b.png)

![image](https://cloud.githubusercontent.com/assets/10272072/9687138/b6b2da14-52f5-11e5-9240-341012b4dd2c.png)

**Comment by michparrish** [comment] 2015-09-04 15:13
I was able to recreate in both pshadow and pclient5, logged in as Gaurang. this item has been forwarded to our QA Dept. Once I receive feedback or a resolution, I will post. Thank you.

**Comment by g4gaurang** [comment] 2015-09-04 15:18
@michparrish Can you confidently rule out any correlation between this issue #243  at this point ? For example, in the past the upload errors attached have been known to occur during timeouts too.

**Comment by michparrish** [comment] 2015-09-04 15:21
I don't logically see a correlation between a simple change to a timeout period and the ability to upload documents, but I have noted this change to our QA Dept as well so they have all of the necessary information. They will work with IT to determine if this had any impact.

**Comment by michparrish** [comment] 2015-09-08 13:57
@g4gaurang our QA dept was able to find that the attributes on some of the 2014 folders are out of sync with the system. This doesn't happen on every 2014 folder and there is no way to know which this impacts. The fix is as follows:
If a user experiences this, please have them click the check box in thebox next to the 2014 folder. 
Go to Tools > Edit Attributes and in that popup, just click Submit. NO changes need to be made to any attributes, just click Submit.
This will realign the attributes for that folder and you shouldn't have any issues uploading new documents into it.
![2014 plan master attribute issue](https://cloud.githubusercontent.com/assets/13471811/9736565/f9008458-560f-11e5-8d22-10a0e45a0936.png)

I have completed this for TJX and Radius Financial.

**Comment by g4gaurang** [comment] 2015-09-08 20:01
@michparrish The suggested fix worked. However, can you figure out a global fix at your end for this issue ? Otherwise, this is just going to be an additional step we will have to add to our process. Also, is there a way you can confirm that we will not run into such issues on 2015 or 2016 folders going forward ?

**Comment by michparrish** [comment] 2015-09-10 15:29
We have opened bug #18727 and working item AB-164 to look into root cause and a fix for this issue.

**Comment by markderg** [comment] 2015-09-11 19:56
Updated to High Severity based on workaround.

**Comment by jddecoste** [comment] 2015-09-14 11:41
Mark, can you please add this one to the RAID log as one you will monitor closely like 183 & 229. We need to ensure this global fix is attended to ASAP. We cannot afford continued manual add-on steps for the team during our heaviest open enrollment period. Thank you

**Comment by markderg** [comment] 2015-09-14 13:53
Yes. I will add this today and post an updated RAID. 

Thanks. Mark

Sent from my iPhone
Please excuse any typos and auto corrections. 

Mark Der Garabedian 
508 776 9426

**Comment by g4gaurang** [comment] 2015-10-23 15:31
Michelle indicated date of 11/18

**Comment by TimHeasley** [comment] 2015-11-06 13:22
Still under investigation by Product team, QA has not been able to reproduce yet.

**Comment by michparrish** [comment] 2015-12-18 16:41
12/18 Memory refreshed:
The reason we received this error message was b/c the user was trying to upload documents to the 2014 plan master folder, which may or may not have attributes associated to it. When there are missing attributes, the upload fails. I have added a note to the JIRA item to ask for additional info on this item so we can report back on a fix. Pending response.

**Comment by markderg** [comment] 2016-01-06 01:10
Confirmed that data fix is being deployed this evening (1/5)  10 pm that should address this issue.  Please validate and follow up tomorrow.  Thx, Mark

**Comment by TimHeasley** [comment] 2016-01-08 15:38
Fix has been deployed to Production, ready for retest.

**Comment by willdwyer** [comment] 2016-01-08 21:59
Looks good.  This is now being closed.

**Closed as completed by willdwyer** 2016-01-08 21:59 UTC
Labels: Type-Defect, Build-P19.5.11.16, Environment-Production, Status- BCBSMA Retest
