### ISSUE TITLE
Not Covered value in any Common Medical Event - Services You May Need should appear into Services Your Plan Does NOT Cover box in Excluded Services

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#263] opened 2015-10-05 19:45 UTC
Hello,

We are requesting an enhancement where that any Service You May Need in Common Medical Event... if a value of "Not Covered" is entered in the In-Network field, that the service would appear in the Services Your Plan Does NOT Cover box under Excluded Services.  See screenshot below as a demonstration.

Please provide LOE and timing for this.

![screen shot 2015-10-05 at 3 43 45 pm](https://cloud.githubusercontent.com/assets/13453008/10291483/fda5f8d0-6b77-11e5-89aa-7e9e83d41b7a.png)

**Comment by michparrish** [comment] 2015-10-05 20:40
Below is the link to the enhancement request form with our details for LOE. Please review, let us know if you want to review together on a call, or let us know if you'd like us to proceed. Thank you.
https://drive.google.com/file/d/0BwDpjEumPUB7SnFrUnppSTZHaXc/view?usp=sharing

**Comment by g4gaurang** [comment] 2015-10-06 14:25
@michparrish,
Thanks for the quick turnaround on the estimates. Just to make it clear,
The requirement is that every time a user indicates "Not covered" for  the lowest cost tier/first cost column against any of the 32 services on the Common Medical Event, the system should indicate that service in the Does Not Cover Box on the SBC Template in the correct alphabetical order. 
             If that service happens to be either or all of the Generic Drugs, Preferred Drugs, Non-Preferred Drugs and/or Specialty Drugs then the system will indicate a single service "Prescription drugs" in the Does Not Cover Box on the SBC Template as representative for any or all of them. Please use the following chart of the exact service label to include in the Does Not Cover Box on the SBC Template:

![image](https://cloud.githubusercontent.com/assets/10272072/10311194/ba856288-6c13-11e5-93cb-be27728069bb.png)

*Nothing needed for Other practitioner office visit

**Comment by michparrish** [comment] 2015-10-06 14:31
thank you - to be clear, when Other practitioner office visit = Not covered, it doesn't need a different naming convention for the bullet OR it does not need to be included in the bullets? Please clarify. Thank you.
Also, please let us know when you decide to move forward with this change.
Thanks.

**Comment by g4gaurang** [comment] 2015-10-06 14:36
> to be clear, when Other practitioner office visit = Not covered, it doesn't need a different naming convention for the bullet OR it does not need to be included in the bullets? Please clarify.

There are two major services that fall under the "Other practitioner office visit" umbrella - Acupuncture and Chiropractic care. Both these services are already in the Excluded Services section and we are able to control their values.

> Also, please let us know when you decide to move forward with this change.

We  approve the 5 hours LOE and can move forward with this change on Pclient5.

**Comment by michparrish** [comment] 2015-10-06 14:41
Thank you - I will respond as to when we can start this work and expected BCBS UAT date.

**Comment by michparrish** [comment] 2015-10-06 14:55
Also, @g4gaurang please confirm what you would want the Generic drugs, Preferred drugs, Non-preferred drugs and Specialty drugs to be called if they are singularly not covered.

**Comment by g4gaurang** [comment] 2015-10-06 14:59
> If that service happens to be **either or all** of the Generic Drugs, Preferred Drugs, Non-Preferred Drugs and/or Specialty Drugs then the system will indicate a single service "Prescription drugs" in the Does Not Cover Box on the SBC Template as representative for any or all of them.

@michparrish hope that answers your question

**Comment by michparrish** [comment] 2015-10-06 15:02
got it, thank you.

**Comment by michparrish** [comment] 2015-10-06 16:39
We will begin this work tomorrow, 10/7, and can deliver for BCBS testing by Wed, 10/14 (forgot that 10/12 is Columbus Day and a HighRoads holiday).

**Comment by TimHeasley** [comment] 2015-10-14 16:17
Will & Guarang,
The Not covered enhancement has been updated in PClient5.  I have tested and confirmed that each of the CME Corresponding values appear correctly.  Please remember when testing the effects of cascading values.  Please test in PClient5 and let us know if you have any questions.
Thank you,
Tim

**Comment by willdwyer** [comment] 2015-10-14 19:28
Hi Tim,

I noticed this change was moved to production (per screenshot).  We never approved the move to production, just PCLIENT5.  I will proceed with testing in the PCLIENT5 environment.

![screen shot 2015-10-14 at 3 28 13 pm](https://cloud.githubusercontent.com/assets/13453008/10495134/47255458-7288-11e5-90b6-82ce1ac1db86.png)

**Comment by g4gaurang** [comment] 2015-10-14 19:29
@TimHeasley Why did you move this change to production directly without formal approval on Pclient5 ?
@markderg @kselvo01

**Comment by TimHeasley** [comment] 2015-10-14 19:37
Will & Gaurang,
The change was not moved to production.  The capture file in Production has a date of August 26, see screenshot.  The new capture file has not been moved, it has only been updated in PClient5.

https://drive.google.com/file/d/0B346D2AloIVGcGxtbFZYSEhGMW8/view?usp=sharing

Thank you,
Tim

**Comment by willdwyer** [comment] 2015-10-14 19:38
Tim,

See above.  My screenshot above was taken just now.

**Comment by g4gaurang** [comment] 2015-10-14 19:39
> Will & Gaurang,
> The change was not moved to production. The capture file in Production has a date of August 26, see screenshot. The new capture file has not been moved, it has only been updated in PClient5.
> 
> https://drive.google.com/file/d/0B346D2AloIVGcGxtbFZYSEhGMW8/view?usp=sharing
> 
> Thank you,
> Tim

See Will's screenshot above. How come we are already seeing the changes applied on production when we change a service to Not covered in-network ?

**Comment by willdwyer** [comment] 2015-10-14 19:53
I tested in PCLIENT5, and it looks good.  However, we encountered a new, separate defect while testing (being logged now).

**Comment by TimHeasley** [comment] 2015-10-14 20:24
I have researched the capture files back to December of 2014 and the same "Not covered" formula has been in use since that time.  I spoke with Steve K and he said that there was a request for creating custom plans and the use of "Not covered". 

The recent capture file updates in PClient5 use the Corresponding Value table above.  In Will's screenshot above you see that in Production - "Primary care visit to treat and injury or illness", in PClient5 the value is "Primary care office visits".  "Preferred brand drugs" in Production is "Prescription drugs" in PClient5. All of the updates in the table have only been made in PClient5 and not moved to Production.

Let me know if you have any questions.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-10-14 21:02
> I have researched the capture files back to December of 2014 and the same "Not covered" formula has been in use since that time. I spoke with Steve K and he said that there was a request for creating custom plans and the use of "Not covered".

Do you have an email with such a request from BCBSMA ?

**Comment by TimHeasley** [comment] 2015-10-15 14:53
Gaurang,
I was not able to find an email, but I was able to find the details from the Issue Log 243 that was opened on 10/22/2014.  See link below for details.

https://drive.google.com/file/d/0B346D2AloIVGeDBOOHdSbjJRRFE/view?usp=sharing

Thank you,
Tim

**Comment by g4gaurang** [comment] 2015-10-15 15:28
> Gaurang,
> I was not able to find an email, but I was able to find the details from the Issue Log 243 that was opened on 10/22/2014. See link below for details.
> 
> https://drive.google.com/file/d/0B346D2AloIVGeDBOOHdSbjJRRFE/view?usp=sharing
> 
> Thank you,
> Tim

In the link above, there is no indirect or  explicit reference to the Covered/Not Covered box issue. 
Also, if this was successfully working in production, we would not have created this enhancement request. Our BEs tried to add Eye exam to the not covered box on the SBC in production but were not able to and tthat is why we created this enhancement request.
![image](https://cloud.githubusercontent.com/assets/10272072/10518424/63fc4eae-732f-11e5-9eb9-03cf816c2cbe.png)

**Comment by michparrish** [comment] 2015-10-22 20:12
Per team mtg on 10/19, please continue testing in pclient5 and once proven successful, we can move the updated configuration into Prod and feel comfortable that Prod is working as needed. 
Thank you.

**Comment by g4gaurang** [comment] 2015-10-26 13:40
When Children's dental check-up and Children's glasses services on the Common Medical Event tab are indicated as not covered, and an SBC generated, they do not show up in the Not covered box IF the user does not take the effort to indicate Not covered for those services also on the Excluded Services Tab. Can you link them so that if user selects/inputs not covered for those services on the common medical event tab (in-network) the values will consequently cascade to those services on the  Excluded Services Tab and show up as Not covered on the SBC ? Otherwise the user will have to enter the same values on both the tabs.

**Comment by michparrish** [comment] 2015-10-26 18:13
@g4gaurang What you're asking for is additional cascading rules. I have a question back to you on this first before we dig into that - do you require the fields to be on both tabs of the Configurator? If the Children's Dental and/or Children's Glasses are covered, does the user also need to denote this on the Excluded Services tab as 'Covered' so they show as bullet points in the 'Other Covered Services' box on the SBC?
If not, we can remove the 2 fields from the Excluded Services tab and only have them on the CME tab, where the user would update the values and when they are 'Not covered' in the INN field, will always show in the 'Services NOT Covered' box as a bullet point.
Please let me know what you think.

**Comment by g4gaurang** [comment] 2015-10-26 20:33
> If not, we can remove the 2 fields from the Excluded Services tab and only have them on the CME tab, where the user would update the values and when they are 'Not covered' in the INN field, will always show in the 'Services NOT Covered' box as a bullet point.
> Please let me know what you think

In which case, IF there was a limitation around either of the Dental Check-up or Glasses services, how would it work if the user indicated Not covered for them on the CME tab ?

**Comment by michparrish** [comment] 2015-10-26 20:54
So you're stating if the CME Children's dental INN value = Not covered, L/E = 'Unless benefits are needed for reconstruction' (for example), in which case you'd expect the bullet point to be added to the Services NOT Covered box that looks like 'Children's dental (Unless benefits are needed for reconstruction)' - correct?

Like with all other CME benefits that are 'Not covered' but may have limitations, they would only show in the 'Services NOT Covered' box as a bullet point and no additional L/E in the parenthesis. Removing the Children's dental and Children's glasses from the Excluded page would make it so only those required 14 benefits for the Excluded Services section have the ability to attach Limitations to the bullet whether they are covered or not.

**Comment by g4gaurang** [comment] 2015-10-27 13:26
I confirmed with BE users that for both Children's dental and Children's glasses the possibility of adding a limitation when Not covered is very low to negligible. You can go ahead with the change. Remove those items from the Excluded Services Tab since they can be controlled directly from the CME tab. I hope the risk of making such a change is low. Please test appropriately before you release to Pclient5.

**Comment by michparrish** [comment] 2015-10-27 13:37
thank you for confirming with the team. We'll move ahead with this change and test it thoroughly. We'll let you know when this is complete and ready for BCBS retest.

**Comment by michparrish** [comment] 2015-10-27 14:50
@g4gaurang 
Quick question - as you know, the CME fields aren't actually named 'Children's glasses' or 'Children's dental'. When 'Glasses' and 'Dental check-up', that both pertain to the section 'If your child needs dental or eye care' section, are listed as Not covered on the CME page, they will show as 'Glasses' and 'Dental check-up' as the bullet point in the Services NOT Covered box. Do you prefer them to say 'Children's glasses' and 'Children's dental' instead or are you ok with them showing the actual field name?

**Comment by g4gaurang** [comment] 2015-10-27 14:53
> @g4gaurang 
> Quick question - as you know, the CME fields aren't actually named 'Children's glasses' or 'Children's dental'. When 'Glasses' and 'Dental check-up', that both pertain to the section 'If your child needs dental or eye care' section, are listed as Not covered on the CME page, they will show as 'Glasses' and 'Dental check-up' as the bullet point in the Services NOT Covered box. Do you prefer them to say 'Children's glasses' and 'Children's dental' instead or are you ok with them showing the actual field name?

We prefer they say 'Children's glasses' and 'Children's dental check-up' in the Does NOT cover box of the SBC just like they do now. Also, do not change the way they are labelled on the CME Tab. Those should replicate the SBC format.

**Comment by TimHeasley** [comment] 2015-10-27 17:18
Guarang,
We have updated the workbooks and capture file. When a “Not Covered” value is entered in the Glasses and/or Dental Check-Up CME fields it will produce Children’s Dental and Children’s Glasses in the Not Covered section of the SBC.

Please retest in PClient5.
Thank you,
Tim

**Comment by g4gaurang** [comment] 2015-10-30 14:49
![image](https://cloud.githubusercontent.com/assets/10272072/10848751/ca4a9254-7ef3-11e5-9560-d94636e6b2e5.png)

This should be Hospices services not Hospice service. Please fix.

**Comment by TimHeasley** [comment] 2015-10-30 17:28
Guarang,
We have updated to "Hospices services".  It has been tested and appears correctly in PClient5.
Please retest and after you confirm/approve we can move to Production.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-10-30 17:41
This looks good. Please move to production.

**Comment by TimHeasley** [comment] 2015-10-30 18:19
Guarang,
The changes have been moved to Production and are ready for retest.
After approval/confirmation please close the issue.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-11-20 15:26
No issues have been reported in production so far. This defect is being closed.

**Closed as completed** 2015-11-20 15:26 UTC
Labels: Build-P19.5.11.16, Environment-Pclient5, Environment-Production, Type-Enhancement, Level_Of_Effort-5_hours, Status- BCBSMA Retest, LOE_Work_Sanctioned
