### ISSUE TITLE
Diabetes calculator not interpreting Does Not Apply to: Most Office Visits correctly

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#328] opened 2015-12-23 17:21 UTC
Hello,

See attached PDF and screenshots below.  The SBC says "Does Not Apply to: Most Office Visits" under "What is the Overall Deductible?", but per diabetes cost calculations, it is interpreting as if Most Office Visits does apply to the overall deductible.  Please see below and fix globally.

[157260BS_Wagamama_PB2K_SB_12-23-2015.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/71067/157260BS_Wagamama_PB2K_SB_12-23-2015.pdf)
![screen shot 2015-12-23 at 11 15 23 am](https://cloud.githubusercontent.com/assets/13453008/11981307/849860b4-a96f-11e5-86be-a94e752f519a.png)
![screen shot 2015-12-23 at 11 14 33 am](https://cloud.githubusercontent.com/assets/13453008/11981306/849843c2-a96f-11e5-9a6d-3446aad19b1a.png)

**Comment by TimHeasley** [comment] 2015-12-29 14:07
Will,
We will research the issue and fix.
Thank you,
Tim

**Comment by TimHeasley** [comment] 2015-12-29 16:49
Hi Will, 
We researched and found that the reason for the issue is that “office visits” is misspelled in the “What is the overall deductible?”.  It currently reads “office vistis” and correcting the spelling appears to correctly interpret it is as deductible not applying.
Please retest at your convenience.
Thanks,
Tim

**Comment by g4gaurang** [comment] 2015-12-30 14:05
Looks good. Closing this issue

**Closed as completed by g4gaurang** 2015-12-30 14:05 UTC
Labels: Type-Defect, Priority-ShowStopper, Environment-Production, Status- BCBSMA Retest
