### ISSUE TITLE
SBC Cost calculator for certain 4 tier pharmacy plans not working correctly

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#255] opened 2015-09-11 14:10 UTC
We have discovered an issue with the cost calculator for 4 tier pharmacy plans.

The cost calculator for a variety of plans is inputting the Generic Mail Order value from the 1st tier, when it was instructed for the cost calculator to input from the 2nd tier.  See below’s screenshot as an example demonstrating this.

Please research and fix globally.

![image](https://cloud.githubusercontent.com/assets/10272072/9816788/185cfeda-586d-11e5-8891-7aae78b10994.png)

**Comment by willdwyer** [comment] 2015-09-11 16:46
Hello, per email, we are still seeing this error.  We encountered it after re-generating a standard PDF from plan design 800007HR_Access_Blue_NE_Basic_2000_80-0117HCCSSG1-1-16.  Please research and fix globally.

**Comment by michparrish** [comment] 2015-09-11 17:38
@willdwyer we looked into it and it's an issue with the data. Make sure there is a close parenthesis on the value and it will work:
![800007hr issue](https://cloud.githubusercontent.com/assets/13471811/9821758/5e0ad14c-588a-11e5-9c36-d0e561f76a49.png)

please retest and let me know if this fixes the issue

**Comment by willdwyer** [comment] 2015-09-11 18:11
Hi Michelle,

For the plan referenced above, after inputting a parentheses ) the calculator was correct.  However, the calculator is still incorrect for 800008HR_Access_Blue_NE_Basic_Saver_80-0118SG1-1-16 (even after inputting the ) )

**Comment by michparrish** [comment] 2015-09-11 20:41
the calculator has been updated into Prod and confirmed fixed. This was fixed globally as the last issue was due to the calculator only looking at the first 2 digits of the Preferred Drug copay and this plan (as well as others) has 3 digits ($125). This formula has been fixed, so now it will recognize 1, 2 and 3 digit values.
Please close item when confirmed this is fixed. Thank you!

**Comment by willdwyer** [comment] 2015-09-15 17:49
Hi Michelle,

This looks to be fixed and can be closed.

**Closed as completed by willdwyer** 2015-09-15 17:49 UTC
Labels: Priority-ShowStopper, Build-P19.5.11.16, Environment-Pclient5, Milestone-Post_1.1, Environment-Production, Status- BCBSMA Retest
