### ISSUE TITLE
Unable to generate - "Distribution Version ID or SBC file are unknown"

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#237] opened 2015-08-07 14:48 UTC
_NOTE_ - this is a reoccurrence of defect 214.

```
1. Log into Production
2. Go to Manage Plan interface
3. Search for: Plan Year - 2016 Product Type - POS Plan Type - Standard
4. Hover over plan 800203HR_Blue_Choice_Value_Plus_80-0125LG1-1-16, create a new custom plan
5. Proceed to save/validate (enter missing fields, but don't edit anything else)
6. Proceed to generate a Draft PDF with disclosures
7. See screenshots.  Unable to generate.
```

![screen shot 2015-08-07 at 10 20 33 am](https://cloud.githubusercontent.com/assets/13453008/9138423/b7c884f4-3cf1-11e5-9ff8-f69d13181016.png)
![screen shot 2015-08-07 at 10 20 38 am](https://cloud.githubusercontent.com/assets/13453008/9138427/b97b6bf4-3cf1-11e5-83d7-4f10a5e3b794.png)

Please fix globally.

**Comment by g4gaurang** [comment] 2015-08-07 14:54
Duplicate of #235 
Being Closed.

**Closed as completed by g4gaurang** 2015-08-07 14:54 UTC
Labels: Type-Defect, Priority-ShowStopper, Build-P19.5.11.16, Milestone-Post_1.1, Environment-Production, Status- New, Status- Closed_Duplicate
