### ISSUE TITLE
Should receive different error message when trying to create a standard plan through configurator

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#233] opened 2015-07-30 18:51 UTC
See screenshots.  PClient5 is correct, while Production is wrong, as this is not a permissions related issue to specific users (no one should be able to do this).
![screen shot 2015-07-30 at 2 52 00 pm](https://cloud.githubusercontent.com/assets/13453008/8992091/ac442552-36ca-11e5-8cbf-76f4b12a8eef.png)
![screen shot 2015-07-30 at 2 04 57 pm](https://cloud.githubusercontent.com/assets/13453008/8992097/b0ba6ace-36ca-11e5-8ac0-d98c17592a3a.png)

**Comment by michparrish** [comment] 2015-07-30 18:59
hi Will - just to confirm, is the 2nd screen shot from Prod? and this is with your user ID or someone else's? please confirm

**Comment by willdwyer** [comment] 2015-07-30 20:08
Hi Michelle,

Yes, this 2nd screenshot is from production, and this was taken with my ID.

**Comment by michparrish** [comment] 2015-07-30 21:01
This is a permissions error, not the editing error. I entered Prod as you and chose both 2015 and 2016 Standard plans to edit and rec'd the correct editing error that you noted in pclient5. It looks like you have 2015 standard plans pulled up in your search - depending on the plan that you chose, you may actually not have access to that version any longer b/c we removed access from the Plan > Draft > Custom or Standard folders after creating the Custom Draft Plan Design folder in plan master. There are quite a few plans in the Plan > Draft > Custom folder that start with 600. I can provide you access to this folder so you can move over whatever plans you want to the new folder, and then shut down access? Please let me know. Thank you.

**Comment by g4gaurang** [comment] 2015-07-31 14:00
This happens also on 2016 plans in production. See screenshot below

![image](https://cloud.githubusercontent.com/assets/10272072/9008622/87750490-3769-11e5-8ea0-002f8266f33e.png)

The error message displayed on Pclient5 is the one that should show up in production.This is the error message we signed off on in Pclient5. But when you repeat the same action is production, the error message is different (permissions error). Please fix.

Pclient5 error message:

![image](https://cloud.githubusercontent.com/assets/10272072/9008724/31f06aea-376a-11e5-9ab8-71130587e0eb.png)

**Comment by michparrish** [comment] 2015-07-31 14:07
please tell me what plan you were choosing when you tried to edit it. Are you getting this error message every time or only with certain plans?

**Comment by g4gaurang** [comment] 2015-07-31 14:13
Every time on all the plans we have tried so far. 
Select any 2016 plan through manage plan search, select "create new plan from this plan" and then select standard and you will notice the permissions error message in production.

**Comment by michparrish** [comment] 2015-07-31 15:03
I see the issue - when 'Creating New Plan From This Plan' for a Standard to a Standard, the Configurator is still making a copy of that Standard plan and placing it in the Plan > Draft > Standard folder, which you don't have access to anymore. THEN the error message is invoked (b/c we only put the error message in place, we did not remove the actual functionality). Just a note: I believe Steve put the error message in as far up in the process as he could. As you know, we changed the mapping of Draft plan designs for Customs only, being that Draft Standards should not be created via the Configurator. I'm looking into having that mapping removed altogether so it breaks that process. If that is a viable solution, I'll circle back for approval. If it is not, I'll keep researching.

**Comment by michparrish** [comment] 2015-08-05 16:38
Update: @willdwyer @g4gaurang @jddecoste 
We tested removing the mapping of the Standard plans to the Plan > Draft > Standard folder in the App Properties but the Configurator is coded to generate a new folder in this location anyway. Therefore, whenever someone tries to Create a New standard plan from a standard plan, a copy is still made and placed into an auto-generated folder. It would be a code enhancement to have code completely removed and much regression testing to ensure nothing else is impacted by this update.

Also, the original Standard plan remains checked out b/c the process is stopped by the permissions limitation midway through the copy process. There is a new copy of the plan still Checked Out as well in the new folder that no one has access to. The new copy of the plan is in 'In Process' state and will show up as an additional plan in the Search Results when a user searches on its criteria.

Therefore, the process here is as follows, without opening an enhancement to update code (either remove the Standard button from use when the user selects which type of New plan they want to create, or remove the code that does the copy in the first place):
- User enters configurator, searches on subset of standard plans
- User selects standard plan and clicks on 'create new plan from this plan' > standard
- Configurator checks out original standard plan to create new copy, creates copy and establishes 'Draft' folder as location to place new copy in
- Process is stopped due to users not having access to this folder location - error message received is one for Permissions to folder and not for running incorrect process to begin with.
  Result: user cannot create new standard plan from standard plan, but original standard plan chosen is checked out and there is a new, in process copy of the plan that no one can get to delete b/c of folder permissions. 
  Additional steps: user would need to find original plan and check back in for other users to access; user would need to open ticket to HR to have someone unlock and remove the new incorrect plan that was copied.

Please let me know if we want to have a quick meeting on this to determine direction. I don't know how much time you/we want to spend on an exception process that should not be taking place anyway.

**Comment by g4gaurang** [comment] 2015-08-05 18:18
@michparrish , so if a user clicks the standard plan button inadvertently, the original base standard plan gets locked out/inaccessible  for others to use. This is a very problematic situation and the manual remedies you suggest above are certainly not desirable since it just adds another step in the already long process for the BEs. 

The risk of a user clicking the standard plan button inadvertently can be effectively mitigated by hiding/disabling the standard plan button on that dialog box. Can you estimate the feasibility and LOE on this?

> The new copy of the plan is in 'In Process' state and will show up as an additional plan in the Search Results when a user searches on its criteria.
- This new copy  in the new folder will not show up as an additional plan in the Search Results when a user searches on its criteria because due to permissions set, the BCBSMA user does not have access to that new folder no ?

Additionally, can you also confirm that when user inadvertently clicks  "edit the plan" on a standard plan from the standard plan search results (and receives the accepted error message) there are no undesirable activities that take place behind the scenes like those noted on this defect ?
![image](https://cloud.githubusercontent.com/assets/10272072/9093284/345fe8e2-3b79-11e5-893e-c0ed895c1824.png)

CC @jddecoste @willdwyer @markderg

**Comment by michparrish** [comment] 2015-08-05 19:14
I'm sorry, I misspoke - the original plan will NOT be checked out/inaccessible when the user selects 'create new plan from this plan > standard'. But a new plan will be copied into the Draft folder and be In Process. This plan does show up in the search results b/c it exists and has copied over the attributes from the base plan. So if you search on the same original criteria after the copy is made, you'll see the original, plus an additional plan with the same name but In Process (you can see I've done this twice):
![standard from a standard](https://cloud.githubusercontent.com/assets/13471811/9095266/5791253c-3b84-11e5-929f-914b516b1234.JPG)

When choosing 'Edit', this is what locks the plan design out. The user would be stopped from entering the configurator with the established error message and they would have to go into Plan Masters to unlock the plan design.

**Comment by g4gaurang** [comment] 2015-08-05 19:42
> But a new plan will be copied into the Draft folder and be In Process. This plan does show up in the search results b/c it exists and has copied over the attributes from the base plan. So if you search on the same original criteria after the copy is made, you'll see the original, plus an additional plan with the same name but In Process (you can see I've done this twice):

Are you sure that is not because you already have access to that draft folder where the unwanted copy is created ? I tried this scenario 5 times on plan 800340HR_Master_Health_Plus_80-0130LGASC1-1-16 and the duplicate copies did not show up either in the content library search Or in the Manage plan search results.

![image](https://cloud.githubusercontent.com/assets/10272072/9095809/5b266542-3b87-11e5-8608-fa99c78343d9.png)

and then 

![image](https://cloud.githubusercontent.com/assets/10272072/9095835/86630c7e-3b87-11e5-979d-eb6a7e2b13e3.png)

**Comment by michparrish** [comment] 2015-08-11 15:01
@g4gaurang 
I conducted some further testing and you are right. In fact, the copy isn't even made so there is no existing 'in process' document if a BCBS user selects 'Create new plan from this plan' > Standard b/c by nnot having permission to the folder it wants to copy to, it cannot create it in the first place.
Therefore, the only issue is when a user selects 'Edit plan' for a standard plan and checks out the original Standard plan. They would be stopped from entering the configurator but we cannot stop the tool from first checking out the doc. I checked with Product and this is base code, as the system was originally supposed to be used to edit Standards as well.
To the original issue here - I cannot change the error message that one receives when selecting 'Create New Plan from this Plan' > Standard b/c the error message means that you don't have access to the folder the system wants to make a copy to. To invoke the approved error message, I need to provide the BCBS team with access to this folder. But then, when the copies are made before reaching Steve’s error, they will remain in that folder and checked out, and now the will come up in Search results as ‘In Process’ plan designs since you now have access to that folder. 
Are we ok keeping this message as the permissions error message? We didn’t find this when testing in pclient5 b/c you all still had access to this folder when we performed this testing on the new error message. 
The user will receive the correct error message when trying to 'Edit Plan' for a standard in the configurator, but they then need to route to that plan design in plan masters and revert it to unlock it.
*A suggestion for users to easily find these items, should this happen, is to show the My WIP Items panel on their dashboard. Then they can click on the location to get directly to that plan design and Revert it.

**Comment by g4gaurang** [comment] 2015-08-18 15:20
> *A suggestion for users to easily find these items, should this happen, is to show the My WIP Items panel on their dashboard. Then they can click on the location to get directly to that plan design and Revert it.

Well, that does not really work does it ? See #245

**Comment by michparrish** [comment] 2015-08-18 17:07
That suggestion was from a week ago before you found that the Location link in the My WIP Items doesn't work.
The current solution offered is for the users to use My WIP Items as an informational panel and then to Search for all items by User = Me, Status = WIP and bulk Check-In these plan designs.

**Comment by markderg** [comment] 2015-08-19 19:15
Recommendation is noted above - The current solution offered is for the users to use My WIP Items as an informational panel and then to Search for all items by User = Me, Status = WIP and bulk Check-In these plan designs.
Recommendation is to close item.

**Comment by g4gaurang** [comment] 2015-08-19 19:31
Issue is being closed. User will receive  a different (permissions) error message in production.

**Closed as completed by g4gaurang** 2015-08-19 19:31 UTC
Labels: Priority-High, Type-Defect, Build-P19.5.11.16, Milestone-Post_1.1, Environment-Production, Status- Pending
