### ISSUE TITLE
Custom plan created in production has #VALUE! in the naming convention

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#234] opened 2015-08-07 14:25 UTC
**What steps will reproduce the problem?**
1. Log on to Production as ggorad01
2. Click on Manage Plan
 Enter search criteria:
 Effective Date - 2016
 Financial Arrangement - Insured
 Market Segment - Large Group 100+
 Product Type - POS
 Plan Type - Standard
 Click - Show Me Plans"
3. Hover cursor over desired plan (800203HR_Blue_Choice_Value_Plus_80-0125LG1-1-16) to select The drop down box with 3 choices will appear
 Select Create a new plan from this plan"
4.Click on Custom Plan Button

**Actual Result:**
On the landing/editing page notice the plan naming convention with HRJobNumber__ #VALUE! in the name. Even the plan name is missing from the naming convention

**Expected Result:**
The plan naming convention  should not have the junk text  #VALUE! in the name.

![image](https://cloud.githubusercontent.com/assets/10272072/9137853/81e46270-3cee-11e5-8296-800b1baad264.png)

After you fix, make sure to test your fix against all standard plans to ensure this does not happen on another random plan before sending it for BCBSMA testing.

**Comment by TimHeasley** [comment] 2015-08-07 15:03
We will look into the issue.

**Comment by TimHeasley** [comment] 2015-08-07 15:41
The system wasn't recognizing the field for some reason, although the field has always been there. We removed and reinstalled it and it is working correctly.  We checked other plans and also updated 800130HR.  Please note we updated the standard plan, you have one plan in the custom folder.  
Ready for retest.

**Comment by g4gaurang** [comment] 2015-08-07 17:30
Not fixed in production. 

![image](https://cloud.githubusercontent.com/assets/10272072/9141652/597c9798-3d08-11e5-9f47-7701a59b504b.png)

**Comment by michparrish** [comment] 2015-08-07 17:54
Working on this again

**Comment by michparrish** [comment] 2015-08-09 21:04
SBC Output File Name (optional) was in incorrect position of plan design. It looks as though this was moved out of place on the source plan design, 600216HR, on 6/30/14 by a former HR employee, perhaps due to a plan design change at that time and a mistake was made.
The field has been put into the position that is required (first, above 'General') and tested and all processes work correctly. This has also been updated in pclient5 if you wish to test things out there.

**Comment by g4gaurang** [comment] 2015-08-10 12:49
Not fixed in production - 

![image](https://cloud.githubusercontent.com/assets/10272072/9171816/9e71faf6-3f3c-11e5-835c-fdbc740c0a8f.png)

**Comment by michparrish** [comment] 2015-08-10 13:19
@g4gaurang what steps are you using to recreate? When I search for 2016, Lg group 100+, Blue Choice Local, Standard and select 800203 > create new plan from this plan, I get the following results:
![value issue](https://cloud.githubusercontent.com/assets/13471811/9172310/d1d7c32c-3f40-11e5-9dbb-bb4f76842bfc.JPG)

**Comment by g4gaurang** [comment] 2015-08-10 15:22
Looks fixed now. Please confirm there are no other Standard HR plan designs where SBC Output File Name (optional) is moved out of place.

**Comment by michparrish** [comment] 2015-08-10 15:43
Confirmed - after finding this, this was included in our QA for the new government field. 

Closing item. Thank you!

**Closed as completed** 2015-08-10 15:44 UTC
Labels: Type-Defect, Priority-ShowStopper, Build-P19.5.11.16, Environment-Production, Status- Closed_Configuration
